module.exports = [
    "Anthem",
    "Attack On Titan 2",
    "A Way Out",
    "BattleTech",
    "Concrete Genie",
    "CrackDown 3",
    "The Crew 2",
    "DarkSiders 3",
    "Detroit Become Human",
    "Dragon Ball Fighterz",
    "Dreams",
    "Extinction",
    "Far Cry 5",
    "FE",
    "The Garden Between",
    "God Of War",
    "Jurassic World Evolution",
    "Kingdom Hearts 3",
    "Kirby Star Allies",
    "Knights And Bikes",
    "The Last Of Us Part 2",
    "Left Alive",
    "The Lord Of The Rings LCG",
    "Mechwarrior 5: Mercenaries",
    "Mega Man 11",
    "Metal Gear Survive",
    "Metro Exodus",
    "Mineko's Night Market",
    "Monster Hunter: World",
    "Ni No Kuni 2: Revenant Kingdom",
    "Red Dead Redemption 2",
    "Return Of The Obra Dinn",
    "Railway Empire",
    "Sea Of Thieves",
    "Shadow Of The Tomb Raider",
    "SoulCalibur 6",
    "Spider-Man",
    "State Of Decay 2",
    "System Shock",
    "Travis Strikes Again: No More Heroes",
    "Tropico 6",
    "Total War Saga: Thrones of Britannia",
    "Valkyria Chronicles 4",
    "Vampyr",
    "Wandersong",
    "WarGames",
    "Wattam",
    "Where The Water Tastes Like Wine",
    "Yoshi"

];
